### ISSUE TITLE
Extended Features

### ISSUE THREAD

**Issue by tusharnankani** [kaustubhgupta/WhatsApp-Groups-Analyser#2]
Came across your project. Brilliant work! @kaustubhgupta ^_^

Recently, I worked on a similar project - [Project Link - An Exhaustive WhatsApp Chat Data Analysis](https://medium.com/@tusharnankani/an-exhaustive-whatsapp-chat-data-analysis-f8421a845c30)

What I have visualized is just of one of my group chats and that too on Jupyter Notebook. I would love to collaborate and brainstorm, if more features are to be added.

**Comment by kaustubhgupta** [comment]
Hi @tusharnankani 
I am glad you liked my project. Soon I would be working on this project again to improve upon some things. I will ping you if I require any additional help!
